# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
