# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='last_use',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
